server:
  port: 8080
  allowOrigins:
    - "*"
  bodyLimit: "10M" # MiB
  timeout: "30s"
 
# oauth2:
#   redirectUrl: "http://localhost:8080/v1/oauth2/google/player/login/callback"
#   clientId: "xxxxx.apps.googleusercontent.com"
#   clientSecret: "xxxxx"
#   endpoints:
#     authUrl: "https://accounts.google.com/o/oauth2/auth?access_type=offline&approval_prompt=force"
#     tokenUrl: "https://oauth2.googleapis.com/token"
#     deviceAuthUrl: "https://oauth2.googleapis.com/device/code"
#   scopes:
#     - "https://www.googleapis.com/auth/userinfo.email"
#     - "https://www.googleapis.com/auth/userinfo.profile"
#   userInfoUrl: "https://www.googleapis.com/oauth2/v2/userinfo"
#   revokeUrl: "https://accounts.google.com/o/oauth2/revoke"

state:
  secret: "0DxgRVY2jzQFOaViB6IYbsWAva8p7gqskl/Q7Q+oUOY="
  expiredsAt: 1800 #second
  issuer: "sun-stockanalysis-api"

database:
  host: localhost
  port: 5432
  user: postgres
  password: root
  dbname: postgres
  sslmode: disable
  schema: stock

finnhub:
  token: "d2unplpr01qq994ghcd0d2unplpr01qq994ghcdg"
